# Java Gradle CircleCI 2.0 configuration file
# See: https://circleci.com/docs/2.0/language-java/
version: 2

orbs:
  heroku: circleci/heroku@1.2.6

jobs:
  build-and-test:
    docker:
      - image: circleci/openjdk:11-jdk
      - image: circleci/postgres:9.4-alpine-ram
auth:
          username: andreasaboc
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
environment:
          POSTGRES_USER: root
          POSTGRES_DB: isa
steps:
      - checkout:
          path: ~/ISA-project
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: sudo apt-get update
      - run: sudo apt-get upgrade
      - run: sudo apt-get install postgresql-client
